-- ============================================================
-- Rosetta Stone Bot - Content Sections & Translations
-- ============================================================
-- Curated: 6 high-value sections covering the project holistically.
-- All icons: Material Symbols Outlined (lowercase).
-- ============================================================
BEGIN;

INSERT INTO content_section (entity_type, entity_id, section_key, icon, position, is_archived, is_pinned)
VALUES
  ('project', (SELECT id FROM project WHERE code = 'rosetta-stone-bot'), 'overview',     'menu_book',   1, false, true),
  ('project', (SELECT id FROM project WHERE code = 'rosetta-stone-bot'), 'motivation',   'gps_fixed',   2, false, false),
  ('project', (SELECT id FROM project WHERE code = 'rosetta-stone-bot'), 'architecture', 'layers',      3, false, true),
  ('project', (SELECT id FROM project WHERE code = 'rosetta-stone-bot'), 'workflow',     'route',       4, false, true),
  ('project', (SELECT id FROM project WHERE code = 'rosetta-stone-bot'), 'deployment',   'inventory_2', 5, false, false),
  ('project', (SELECT id FROM project WHERE code = 'rosetta-stone-bot'), 'challenges',   'warning',     6, false, false)
ON CONFLICT DO NOTHING;

INSERT INTO content_section_translation (content_section_id, language_id, title, body)
VALUES
  -- overview
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'overview' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'es'), 'Descripción General',
   E'Bot de automatización para **Rosetta Stone** construido con **Playwright** y **Python 3.13** que simula la interacción real de un usuario con la plataforma de aprendizaje de idiomas.\n\nA diferencia del Script A (que usa APIs directamente), este bot opera a nivel de UI: automatiza el login institucional, navega por la interfaz, selecciona historias y lecciones, y ejecuta ciclos infinitos de escucha y lectura hasta alcanzar una meta de horas configurable (por defecto 35h).\n\nSoporta ejecución multi-usuario concurrente mediante Docker Compose, donde cada estudiante se configura como un servicio independiente con su propio archivo de credenciales y un volumen compartido para tracking de progreso.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'overview' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'en'), 'Overview',
   E'Automation bot for **Rosetta Stone** built with **Playwright** and **Python 3.13** that simulates a real user''s interaction with the language learning platform.\n\nUnlike Script A (which uses APIs directly), this bot operates at the UI level: it automates institutional login, navigates the interface, selects stories and lessons, and runs infinite listen/read cycles until reaching a configurable hour target (default 35h).\n\nSupports concurrent multi-user execution via Docker Compose, where each student is configured as an independent service with their own credentials file and a shared volume for progress tracking.'),

  -- motivation
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'motivation' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'es'), 'Motivación',
   E'El programa universitario de inglés requiere **35 horas** de práctica en Rosetta Stone por estudiante por semestre. Acumular estas horas manualmente implica sesiones diarias de 30-60 minutos durante meses, con contenido repetitivo que no contribuye significativamente al aprendizaje real.\n\nEl bot automatiza esta acumulación de forma completamente desatendida: se ejecuta en segundo plano (o en un servidor Docker), simula la actividad de práctica navegando lecciones y reproduciendo audio, y registra el progreso hasta alcanzar la meta configurada. Múltiples estudiantes pueden ejecutarse simultáneamente, cada uno con sus credenciales independientes.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'motivation' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'en'), 'Motivation',
   E'The university English program requires **35 hours** of Rosetta Stone practice per student per semester. Accumulating these hours manually involves daily 30-60 minute sessions over months, with repetitive content that doesn''t significantly contribute to real learning.\n\nThe bot automates this accumulation completely unattended: it runs in the background (or on a Docker server), simulates practice activity by navigating lessons and playing audio, and tracks progress until reaching the configured target. Multiple students can run simultaneously, each with their independent credentials.'),

  -- architecture
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'architecture' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'es'), 'Arquitectura',
   E'Arquitectura limpia en capas donde cada módulo tiene una responsabilidad clara y expone su API pública vía `__init__.py`:\n\n• **core/** — Constantes globales y configuración del logger\n• **config/** — Dataclasses de configuración cargadas desde variables de entorno (.env)\n• **browser/** — Ciclo de vida de Chromium: creación, configuración de viewport, y cierre\n• **locators/** — Selectores CSS centralizados y patrones regex bilingües (español/inglés) para elementos de UI\n• **components/** — Wrappers de modals de UI (audio, voz, confirmación) con auto-dismiss\n• **pages/** — Page Object Model: Login, Launchpad, Stories, Lesson — cada página encapsula sus interacciones\n• **services/** — AudioPlayer (reproducción controlada), TimeTracker (persistencia JSON de sesiones), Debug (screenshots)\n• **workflows/** — StoriesWorkflow y LessonWorkflow: orquestadores de alto nivel que coordinan páginas y servicios'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'architecture' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'en'), 'Architecture',
   E'Clean layered architecture where each module has a clear responsibility and exposes its public API via `__init__.py`:\n\n• **core/** — Global constants and logger configuration\n• **config/** — Configuration dataclasses loaded from environment variables (.env)\n• **browser/** — Chromium lifecycle: creation, viewport setup, and teardown\n• **locators/** — Centralized CSS selectors and bilingual regex patterns (Spanish/English) for UI elements\n• **components/** — UI modal wrappers (audio, voice, confirmation) with auto-dismiss\n• **pages/** — Page Object Model: Login, Launchpad, Stories, Lesson — each page encapsulates its interactions\n• **services/** — AudioPlayer (controlled playback), TimeTracker (JSON session persistence), Debug (screenshots)\n• **workflows/** — StoriesWorkflow and LessonWorkflow: high-level orchestrators coordinating pages and services'),

  -- workflow
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'workflow' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'es'), 'Flujo de Automatización',
   E'El bot ejecuta un ciclo continuo hasta alcanzar la meta de horas:\n\n1. **Login** — Ingresa credenciales institucionales y maneja captchas/confirmaciones\n2. **Navegación** — Accede al launchpad principal del curso\n3. **Selección de modo** — Elige entre Stories (contenido narrativo) o Lesson (ejercicios estructurados)\n4. **Ciclo infinito:**\n   • Descubre contenido disponible en la lección/historia actual\n   • Reproduce audio del ejercicio con esperas calibradas\n   • Alterna entre modos Listen y Read para simular práctica activa\n   • Detecta cuando la lección se completa y reinicia con la siguiente\n5. **Tracking** — El TimeTracker registra cada sesión en un archivo JSON compartido, acumulando horas hasta la meta\n\nEl bot maneja automáticamente dialogs del navegador (`page.on("dialog")`), modals inesperados de audio/voz con auto-dismiss, y fallback de selectores SVG cuando los controles de audio cambian de forma.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'workflow' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'en'), 'Automation Flow',
   E'The bot runs a continuous cycle until reaching the hour target:\n\n1. **Login** — Enters institutional credentials and handles captchas/confirmations\n2. **Navigation** — Accesses the main course launchpad\n3. **Mode selection** — Chooses between Stories (narrative content) or Lesson (structured exercises)\n4. **Infinite cycle:**\n   • Discovers available content in the current lesson/story\n   • Plays exercise audio with calibrated waits\n   • Alternates between Listen and Read modes to simulate active practice\n   • Detects lesson completion and restarts with the next one\n5. **Tracking** — TimeTracker records each session in a shared JSON file, accumulating hours toward the target\n\nThe bot automatically handles browser dialogs (`page.on("dialog")`), unexpected audio/voice modals with auto-dismiss, and SVG selector fallback when audio controls change shape.'),

  -- deployment
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'deployment' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'es'), 'Despliegue Docker',
   E'Entorno containerizado diseñado para ejecución multi-usuario desatendida:\n\n• **Dockerfile** basado en `python:3.13-slim` con dependencias de sistema para Playwright (Chromium headless), `uv` como gestor de paquetes ultrarrápido, e instalación automática de browsers\n• **Docker Compose** define un servicio por usuario/estudiante, cada uno con su propio `env_file` conteniendo credenciales individuales\n• **Volumen compartido** `tracking-data` montado en `/app/data` donde todos los servicios escriben su progreso en archivos JSON independientes\n• **Política de reinicio** `restart: always` para auto-recuperación ante caídas del browser, errores de red o timeouts de sesión\n\nEsta configuración permite ejecutar 10+ estudiantes simultáneamente en un solo servidor, cada uno acumulando horas de forma independiente.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'deployment' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'en'), 'Docker Deployment',
   E'Containerized environment designed for unattended multi-user execution:\n\n• **Dockerfile** based on `python:3.13-slim` with system dependencies for Playwright (headless Chromium), `uv` as ultrafast package manager, and automatic browser installation\n• **Docker Compose** defines one service per user/student, each with their own `env_file` containing individual credentials\n• **Shared volume** `tracking-data` mounted at `/app/data` where all services write their progress to independent JSON files\n• **Restart policy** `restart: always` for auto-recovery from browser crashes, network errors, or session timeouts\n\nThis setup allows running 10+ students simultaneously on a single server, each accumulating hours independently.'),

  -- challenges
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'challenges' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'es'), 'Desafíos Técnicos',
   E'**UI bilingüe** — La interfaz de Rosetta Stone alterna entre español e inglés según la configuración. Los selectores usan regex compilado (`escuchar|listen`, `lecciones|lessons`) para funcionar independientemente del idioma activo.\n\n**Controles SVG dinámicos** — Los botones de audio usan elementos SVG que cambian de forma según el estado (play/pause). El bot implementa fallback `polygon→circle` para detectar el estado correcto del reproductor.\n\n**Contenido en iframes anidados** — Las lecciones se cargan dentro de iframes que a su vez contienen más iframes. La búsqueda de elementos se realiza de forma recursiva a través de todos los niveles de anidamiento.\n\n**Modals aleatorios** — Rosetta Stone muestra popups imprevistos de audio, micrófono y confirmación. El bot los detecta y cierra automáticamente sin interrumpir el flujo principal.\n\n**Persistencia concurrente** — Múltiples instancias Docker escriben en archivos JSON del mismo volumen. El sistema usa locks de archivo para evitar corrupción de datos.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_id = (SELECT id FROM project WHERE code = 'rosetta-stone-bot') AND cs.section_key = 'challenges' AND cs.entity_type = 'project'),
   (SELECT id FROM language WHERE code = 'en'), 'Technical Challenges',
   E'**Bilingual UI** — Rosetta Stone''s interface alternates between Spanish and English based on configuration. Selectors use compiled regex (`escuchar|listen`, `lecciones|lessons`) to work regardless of the active language.\n\n**Dynamic SVG controls** — Audio buttons use SVG elements that change shape based on state (play/pause). The bot implements `polygon→circle` fallback to detect the correct player state.\n\n**Nested iframe content** — Lessons load inside iframes that in turn contain more iframes. Element search is performed recursively through all nesting levels.\n\n**Random modals** — Rosetta Stone shows unexpected audio, microphone, and confirmation popups. The bot detects and closes them automatically without interrupting the main flow.\n\n**Concurrent persistence** — Multiple Docker instances write to JSON files on the same volume. The system uses file locks to prevent data corruption.')
ON CONFLICT (content_section_id, language_id) DO NOTHING;

COMMIT;
