-- =========================
-- Enable Row Level Security
-- =========================

-- Base tables
ALTER TABLE skill_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE event ENABLE ROW LEVEL SECURITY;
ALTER TABLE project ENABLE ROW LEVEL SECURITY;
ALTER TABLE image ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_usages ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE cv_document ENABLE ROW LEVEL SECURITY;


-- Translation tables (new pattern)
ALTER TABLE skill_category_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitions_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE experience_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_usages_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile_translation ENABLE ROW LEVEL SECURITY;
