BEGIN;

INSERT INTO content_section (id, entity_type, entity_id, section_key, icon, position, is_archived, is_pinned)
VALUES
  (1,  'project', 1,  'overview',     'folder_open',   1, false, true),
  (2,  'project', 1,  'architecture', 'account_tree',  2, false, true),
  (3,  'project', 1,  'tech_stack',   'layers',        3, false, false),
  (4,  'project', 2,  'overview',     'web',           1, false, true),
  (5,  'project', 2,  'features',     'star',          2, false, false),
  (6,  'project', 3,  'overview',     'dns',           1, false, true),
  (7,  'project', 3,  'architecture', 'account_tree',  2, false, true),
  (8,  'project', 3,  'testing',      'science',       3, false, false),
  (9,  'project', 4,  'overview',     'lock',          1, false, true),
  (10, 'project', 4,  'features',     'vpn_key',       2, false, false),
  (11, 'project', 5,  'overview',     'hub',           1, false, true),
  (12, 'project', 5,  'features',     'merge_type',    2, false, false),
  (13, 'project', 6,  'overview',     'smart_toy',     1, false, true),
  (14, 'project', 6,  'features',     'psychology',    2, false, false),
  (15, 'project', 7,  'overview',     'payments',      1, false, true),
  (16, 'project', 8,  'overview',     'sync_alt',      1, false, true),
  (17, 'project', 9,  'overview',     'memory',        1, false, true),
  (18, 'project', 10, 'overview',     'storefront',    1, true,  false),
  (19, 'project', 11, 'overview',     'table_bar',     1, false, true),
  (20, 'project', 12, 'overview',     'restaurant',    1, false, false),
  (21, 'project', 13, 'overview',     'event_seat',    1, false, false),
  (22, 'project', 14, 'overview',     'menu_book',     1, false, false),
  (23, 'project', 15, 'overview',     'rate_review',   1, false, false),
  (24, 'project', 16, 'overview',     'receipt_long',  1, false, false),
  (25, 'project', 17, 'overview',     'card_membership',1,false, false),
  (26, 'project', 18, 'overview',     'data_object',   1, false, false),
  (27, 'project', 19, 'overview',     'verified',      1, false, false),
  (28, 'project', 20, 'overview',     'map',           1, false, true),
  (29, 'project', 21, 'overview',     'grid_on',       1, false, false),
  (30, 'project', 22, 'overview',     'translate',     1, false, false),
  (31, 'project', 23, 'overview',     'settings',      1, false, false),
  (32, 'project', 24, 'overview',     'playlist_add',  1, false, false),
  (33, 'project', 25, 'overview',     'admin_panel_settings',1,false,false),
  (34, 'project', 26, 'overview',     'chat',          1, false, false),
  (35, 'project', 27, 'overview',     'language',      1, false, false),
  (36, 'project', 28, 'overview',     'stream',        1, false, false),
  (37, 'project', 29, 'overview',     'auto_fix_high', 1, false, false),
  (38, 'project', 30, 'overview',     'cloud',         1, false, true)
ON CONFLICT (id) DO NOTHING;

SELECT setval('content_section_id_seq', (SELECT COALESCE(MAX(id),0) FROM content_section));

INSERT INTO content_section_translation (content_section_id, language_id, title, body) VALUES
(1,1,'Descripción General','mesaYA es una plataforma de reservas de restaurantes con arquitectura de microservicios. Conecta clientes con restaurantes mediante reservas en tiempo real, chatbot con IA, pagos en línea y mapas interactivos de mesas.'),
(1,2,'Overview','mesaYA is a restaurant reservation platform with microservices architecture. It connects customers with restaurants through real-time reservations, AI chatbot, online payments, and interactive table maps.'),
(2,1,'Arquitectura','Frontend Angular 19 (SSR), API de Reservas (NestJS + DDD), Auth MS (NestJS + RBAC), GraphQL Gateway (Python + Strawberry), Chatbot (Python), Payment MS (NestJS), WebSocket Service y MCP. Comunicación asíncrona con Kafka y orquestación con Docker Compose.'),
(2,2,'Architecture','Angular 19 Frontend (SSR), Reservation API (NestJS + DDD), Auth MS (NestJS + RBAC), GraphQL Gateway (Python + Strawberry), Chatbot (Python), Payment MS (NestJS), WebSocket Service, and MCP. Async communication via Kafka and orchestration with Docker Compose.'),
(3,1,'Stack Tecnológico','TypeScript, Angular 19, NestJS, Python, Strawberry GraphQL, PostgreSQL, TypeORM, Kafka, Docker, Jest, SonarQube, GitHub Actions, JWT, Swagger.'),
(3,2,'Tech Stack','TypeScript, Angular 19, NestJS, Python, Strawberry GraphQL, PostgreSQL, TypeORM, Kafka, Docker, Jest, SonarQube, GitHub Actions, JWT, Swagger.'),
(4,1,'Descripción General','SPA con Angular 19 y SSR. Mapas interactivos de restaurantes en canvas, selección de mesas en tiempo real vía WebSocket, internacionalización (es/en), Material Design y lazy loading por features.'),
(4,2,'Overview','SPA with Angular 19 and SSR. Interactive restaurant maps on canvas, real-time table selection via WebSocket, internationalization (es/en), Material Design, and feature-based lazy loading.'),
(5,1,'Funcionalidades Clave','Mapa canvas interactivo con secciones y mesas, selección en tiempo real con WebSocket, cambio de idioma persistente, modal de configuración, adaptadores de repositorio para HTTP y WS, y diseño responsivo.'),
(5,2,'Key Features','Interactive canvas map with sections and tables, real-time selection with WebSocket, persistent language switch, settings modal, repository adapters for HTTP and WS, and responsive design.'),
(6,1,'Descripción General','Microservicio principal que gestiona restaurantes, secciones, mesas, menús, reservas, reseñas, pagos y suscripciones. NestJS con Clean Architecture y DDD, entidades ricas y Value Objects.'),
(6,2,'Overview','Core microservice managing restaurants, sections, tables, menus, reservations, reviews, payments, and subscriptions. NestJS with Clean Architecture and DDD, rich entities and Value Objects.'),
(7,1,'Arquitectura','Capas: Domain (entidades, VOs, eventos), Application (casos de uso, puertos), Infrastructure (TypeORM, Kafka, mappers) e Interface (controladores REST, Swagger). Patrón Facade para seeding en 5 fases.'),
(7,2,'Architecture','Layers: Domain (entities, VOs, events), Application (use cases, ports), Infrastructure (TypeORM, Kafka, mappers), and Interface (REST controllers, Swagger). Facade pattern for 5-phase seeding.'),
(8,1,'Testing y Calidad','Cobertura de tests unitarios al 90% con Jest. SonarCloud vía GitHub Actions con Quality Gate personalizado, análisis de code smells y cobertura LCOV.'),
(8,2,'Testing & Quality','90% unit test coverage with Jest. SonarCloud via GitHub Actions with custom Quality Gate, code smells analysis, and LCOV coverage.'),
(9,1,'Descripción General','Microservicio de autenticación con JWT y RBAC completo. Usuarios, roles y permisos con seeding automático al iniciar vía OnModuleInit.'),
(9,2,'Overview','Authentication microservice with JWT and complete RBAC. Users, roles, and permissions with automatic seeding on startup via OnModuleInit.'),
(10,1,'Funcionalidades','Registro e inicio de sesión con JWT + refresh tokens, hash de contraseñas, asignación dinámica de permisos, roles predefinidos (admin, owner, user, guest) y middleware de verificación.'),
(10,2,'Features','Registration and login with JWT + refresh tokens, password hashing, dynamic permission assignment, predefined roles (admin, owner, user, guest), and verification middleware.'),
(11,1,'Descripción General','Gateway GraphQL en Python con Strawberry que agrega las APIs REST de los microservicios bajo un schema unificado. Arquitectura modular por features.'),
(11,2,'Overview','Python GraphQL gateway with Strawberry aggregating microservice REST APIs under a unified schema. Feature-based modular architecture.'),
(12,1,'Funcionalidades','Queries y mutations para restaurantes, mesas, reservas y autenticación. Resolvers que consumen endpoints REST con manejo de errores centralizado.'),
(12,2,'Features','Queries and mutations for restaurants, tables, reservations, and authentication. Resolvers consuming REST endpoints with centralized error handling.'),
(13,1,'Descripción General','Servicio de chatbot con IA que genera prompts contextuales según el nivel de acceso (GUEST, USER, OWNER, ADMIN) y el idioma (es/en).'),
(13,2,'Overview','AI chatbot service generating contextual prompts based on access level (GUEST, USER, OWNER, ADMIN) and language (es/en).'),
(14,1,'Funcionalidades','Prompts especializados por rol con conocimiento de dominio (cliente busca restaurantes vs dueño gestiona negocio). Soporte bilingüe completo.'),
(14,2,'Features','Role-specialized prompts with domain knowledge (client searching restaurants vs owner managing business). Full bilingual support.'),
(15,1,'Descripción General','Microservicio de pagos para transacciones de reservas y suscripciones con Value Objects para moneda y estado.'),
(15,2,'Overview','Payment microservice for reservation and subscription transactions with Value Objects for currency and status.'),
(16,1,'Descripción General','WebSockets para comunicación bidireccional en tiempo real: selección/liberación de mesas, actualizaciones de estado y notificaciones push.'),
(16,2,'Overview','WebSockets for real-time bidirectional communication: table selection/release, status updates, and push notifications.'),
(17,1,'Descripción General','Integración con Model Context Protocol para proporcionar contexto del sistema a asistentes de IA y herramientas de desarrollo.'),
(17,2,'Overview','Model Context Protocol integration to provide system context to AI assistants and development tools.'),
(18,1,'Descripción General','Aplicación de demostración para socios comerciales. Archivada tras completar fase de presentación.'),
(18,2,'Overview','Demo application for business partners. Archived after presentation phase completed.'),
(19,1,'Descripción General','Entidad rica Table con validación de layout (colisiones, límites), snapshot/rehydrate, analíticas y eventos Kafka para sincronización en tiempo real.'),
(19,2,'Overview','Rich Table entity with layout validation (collisions, bounds), snapshot/rehydrate, analytics, and Kafka events for real-time sync.'),
(20,1,'Descripción General','Gestión de restaurantes con horarios, días de operación, ubicación y capacidad. Verificación de propietarios vía Auth MS.'),
(20,2,'Overview','Restaurant management with schedules, operating days, location, and capacity. Owner verification via Auth MS.'),
(21,1,'Descripción General','Reservaciones con máquina de estados, validación de disponibilidad y relación usuario-restaurante-mesa.'),
(21,2,'Overview','Reservations with state machine, availability validation, and user-restaurant-table relationships.'),
(22,1,'Descripción General','Gestión de menús y platos por restaurante con precios, descripciones e imágenes.'),
(22,2,'Overview','Menu and dish management per restaurant with prices, descriptions, and images.'),
(23,1,'Descripción General','Calificaciones y comentarios de usuarios sobre restaurantes con valoración numérica.'),
(23,2,'Overview','User ratings and comments for restaurants with numeric scores.'),
(24,1,'Descripción General','Procesamiento de pagos para reservaciones y suscripciones con VOs de moneda y estado de transacción.'),
(24,2,'Overview','Payment processing for reservations and subscriptions with currency and transaction status VOs.'),
(25,1,'Descripción General','Planes de suscripción para restaurantes con estados activo/inactivo y fechas de vigencia.'),
(25,2,'Overview','Restaurant subscription plans with active/inactive states and validity dates.'),
(26,1,'Descripción General','Orquestador de seeding con patrón Facade: planes → media → restaurantes → secciones → mesas → menús → reservas → reseñas → pagos.'),
(26,2,'Overview','Seeding orchestrator with Facade pattern: plans → media → restaurants → sections → tables → menus → reservations → reviews → payments.'),
(27,1,'Descripción General','SonarCloud con GitHub Actions, cobertura LCOV al 90%, Quality Gate personalizado y análisis continuo de deuda técnica.'),
(27,2,'Overview','SonarCloud with GitHub Actions, 90% LCOV coverage, custom Quality Gate, and continuous technical debt analysis.'),
(28,1,'Descripción General','Componente canvas interactivo que renderiza secciones y mesas con assets visuales, estados de disponibilidad y selección en tiempo real.'),
(28,2,'Overview','Interactive canvas component rendering sections and tables with visual assets, availability states, and real-time selection.'),
(29,1,'Descripción General','Adaptador que unifica datos de mesas desde HTTP y WebSocket con mapeo robusto de payloads polimórficos.'),
(29,2,'Overview','Adapter unifying table data from HTTP and WebSocket with robust polymorphic payload mapping.'),
(30,1,'Descripción General','Sistema de traducción con TranslatePipe, I18nPort abstracto, soporte es/en y persistencia de preferencia de idioma.'),
(30,2,'Overview','Translation system with TranslatePipe, abstract I18nPort, es/en support, and language preference persistence.'),
(31,1,'Descripción General','Modal de configuración con selector de idioma y preferencias de la aplicación.'),
(31,2,'Overview','Settings modal with language selector and application preferences.'),
(32,1,'Descripción General','Siembra automática de permisos, roles y usuarios por defecto al iniciar con OnModuleInit de NestJS.'),
(32,2,'Overview','Automatic seeding of permissions, roles, and default users on startup with NestJS OnModuleInit.'),
(33,1,'Descripción General','RBAC con permisos granulares, roles predefinidos (admin, owner, user, guest) y asignación dinámica.'),
(33,2,'Overview','RBAC with granular permissions, predefined roles (admin, owner, user, guest), and dynamic assignment.'),
(34,1,'Descripción General','Generación de prompts por nivel de acceso con conocimiento de dominio especializado para cada rol.'),
(34,2,'Overview','Prompt generation by access level with specialized domain knowledge for each role.'),
(35,1,'Descripción General','Módulo de idiomas soportados con español por defecto e inglés como alternativa.'),
(35,2,'Overview','Supported languages module with Spanish as default and English as alternative.'),
(36,1,'Descripción General','Brokers Kafka, topics de eventos de dominio y conectores para comunicación asíncrona entre microservicios.'),
(36,2,'Overview','Kafka brokers, domain event topics, and connectors for async communication between microservices.'),
(37,1,'Descripción General','Flujos de automatización con n8n para integraciones y workflows del ecosistema mesaYA.'),
(37,2,'Overview','Automation flows with n8n for integrations and workflows of the mesaYA ecosystem.'),
(38,1,'Descripción General','Docker Compose con PostgreSQL, Kafka, Zookeeper, n8n y todos los microservicios. Redes, volúmenes y variables de entorno.'),
(38,2,'Overview','Docker Compose with PostgreSQL, Kafka, Zookeeper, n8n, and all microservices. Networks, volumes, and environment variables.')
ON CONFLICT (content_section_id, language_id) DO NOTHING;

COMMIT;
