-- ============================================================
-- StreamFlow Music - Content Sections & Translations
-- ============================================================
-- Icons: Material Icons | Languages: es/en via SELECT
BEGIN;

-- ============================================================
-- MONOREPO: streamflow-music
-- ============================================================
INSERT INTO content_section (entity_type, entity_id, section_key, icon, position, is_archived, is_pinned)
VALUES
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music'), 'overview',      'info',          1, false, true),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music'), 'architecture',  'account_tree',  2, false, true),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music'), 'tech_stack',    'layers',        3, false, false),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music'), 'agile_overview','groups',        4, false, true),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music'), 'sprint_process','replay',        5, false, true),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music'), 'moscow',        'priority_high', 6, false, false),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music'), 'kanban',        'view_kanban',   7, false, false),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music'), 'burndown',      'trending_down', 8, false, false),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music'), 'challenges',    'warning',       9, false, false)
ON CONFLICT DO NOTHING;

INSERT INTO content_section_translation (content_section_id, language_id, title, body)
VALUES
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'overview'),
   (SELECT id FROM language WHERE code = 'es'), 'Descripción General',
   E'StreamFlow Music es una plataforma de streaming de música full-stack organizada como monorepo con submódulos Git que vinculan los repositorios de backend y frontend de forma independiente.\n\nEl proyecto nace como una exploración práctica de cómo construir una plataforma completa de streaming aplicando Arquitectura Limpia en dos ecosistemas distintos (Python/Django y Angular/TypeScript), manteniendo consistencia arquitectónica y calidad de código centralizada.\n\nOfrece infraestructura Supabase compartida para autenticación, base de datos y almacenamiento, quality gates centralizados mediante SonarCloud con proyectos separados para cada codebase, y orquestación de servicios con Docker Compose para desarrollo local y despliegue.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'overview'),
   (SELECT id FROM language WHERE code = 'en'), 'Overview',
   E'StreamFlow Music is a full-stack music streaming platform organized as a monorepo with Git submodules linking the backend and frontend repositories independently.\n\nThe project was born as a practical exploration of building a complete streaming platform applying Clean Architecture across two distinct ecosystems (Python/Django and Angular/TypeScript), maintaining architectural consistency and centralized code quality.\n\nIt provides shared Supabase infrastructure for authentication, database, and storage, centralized quality gates via SonarCloud with separate projects for each codebase, and service orchestration with Docker Compose for local development and deployment.'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'architecture'),
   (SELECT id FROM language WHERE code = 'es'), 'Arquitectura',
   E'El monorepo sigue una estructura basada en submódulos donde cada proyecto hijo (backend y frontend) implementa independientemente Arquitectura Limpia con capas de dominio, casos de uso, infraestructura y presentación.\n\nEl backend utiliza Django REST Framework con una separación estricta: entidades de dominio puras (SongEntity), interfaces de repositorio, casos de uso orquestadores (SaveTrackAsSongUseCase) y una capa API con ViewSets y serializadores.\n\nEl frontend aplica el mismo patrón con casos de uso (AuthSessionUseCase, ChangeLanguageUseCase), interfaces de repositorio con tokens de inyección (LANGUAGE_REPOSITORY_TOKEN), implementaciones concretas y servicios de presentación con signals reactivos.\n\nDocker Compose orquesta ambos servicios junto con PostgreSQL para desarrollo local unificado.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'architecture'),
   (SELECT id FROM language WHERE code = 'en'), 'Architecture',
   E'The monorepo follows a submodule-based structure where each child project (backend and frontend) independently implements Clean Architecture with domain, use cases, infrastructure, and presentation layers.\n\nThe backend uses Django REST Framework with strict separation: pure domain entities (SongEntity), repository interfaces, orchestrating use cases (SaveTrackAsSongUseCase), and an API layer with ViewSets and serializers.\n\nThe frontend applies the same pattern with use cases (AuthSessionUseCase, ChangeLanguageUseCase), repository interfaces with injection tokens (LANGUAGE_REPOSITORY_TOKEN), concrete implementations, and presentation services with reactive signals.\n\nDocker Compose orchestrates both services alongside PostgreSQL for unified local development.'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'tech_stack'),
   (SELECT id FROM language WHERE code = 'es'), 'Stack Tecnológico',
   E'**Backend:** Python 3.11+ · Django 5 · Django REST Framework · drf-spectacular (OpenAPI) · pytest · Supabase SDK\n**Frontend:** Angular 19+ · TypeScript · SCSS · ngx-translate · Supabase JS · Compodoc\n**Infraestructura:** PostgreSQL · Supabase (Auth + Storage + DB) · Docker Compose · SonarCloud · Git Submodules\n**CI/CD:** GitHub Actions con análisis automático de calidad y tests en cada push'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'tech_stack'),
   (SELECT id FROM language WHERE code = 'en'), 'Tech Stack',
   E'**Backend:** Python 3.11+ · Django 5 · Django REST Framework · drf-spectacular (OpenAPI) · pytest · Supabase SDK\n**Frontend:** Angular 19+ · TypeScript · SCSS · ngx-translate · Supabase JS · Compodoc\n**Infrastructure:** PostgreSQL · Supabase (Auth + Storage + DB) · Docker Compose · SonarCloud · Git Submodules\n**CI/CD:** GitHub Actions with automated quality analysis and tests on every push'),

  -- Agile Overview ES
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'agile_overview'),
   (SELECT id FROM language WHERE code = 'es'), 'Metodología Ágil',
   E'StreamFlow Music se desarrolló aplicando Scrum como marco de trabajo ágil con ceremonias completas y artefactos definidos a lo largo de todo el ciclo de vida del proyecto.\n\nEl equipo siguió sprints de duración fija con todas las ceremonias Scrum implementadas: Sprint Planning para definir el alcance de cada iteración, Daily Stand-ups para sincronización diaria del equipo, Sprint Review para demostración de incrementos funcionales, y Sprint Retrospective para mejora continua del proceso.\n\nSe aplicó priorización MoSCoW (Must have, Should have, Could have, Won''t have) para gestionar el backlog del producto, garantizando que las funcionalidades críticas se entregaran primero y que el alcance de cada sprint fuera realista y medible.'),
  -- Agile Overview EN
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'agile_overview'),
   (SELECT id FROM language WHERE code = 'en'), 'Agile Methodology',
   E'StreamFlow Music was developed applying Scrum as the agile framework with complete ceremonies and defined artifacts throughout the entire project lifecycle.\n\nThe team followed fixed-length sprints with all Scrum ceremonies implemented: Sprint Planning to define the scope of each iteration, Daily Stand-ups for daily team synchronization, Sprint Review for demonstration of functional increments, and Sprint Retrospective for continuous process improvement.\n\nMoSCoW prioritization (Must have, Should have, Could have, Won''t have) was applied to manage the product backlog, ensuring critical features were delivered first and that each sprint''s scope was realistic and measurable.'),

  -- Sprint Process ES
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'sprint_process'),
   (SELECT id FROM language WHERE code = 'es'), 'Ceremonias de Sprint',
   E'Cada sprint seguía un ciclo estructurado de ceremonias que garantizaban transparencia, inspección y adaptación:\n\n• **Sprint Planning** — Sesión de planificación al inicio de cada sprint donde se seleccionaban historias de usuario del backlog priorizado con MoSCoW, se estimaban con puntos de historia y se descomponían en tareas técnicas asignables\n• **Daily Stand-up** — Reunión diaria de sincronización de 15 minutos donde cada miembro del equipo compartía progreso, impedimentos y plan del día. Mantenía la visibilidad del estado del sprint y permitía detectar bloqueos tempranamente\n• **Sprint Review** — Demostración del incremento funcional al final de cada sprint, mostrando las funcionalidades completadas (reproductor de música, gestión de playlists, autenticación, etc.) y recopilando feedback\n• **Sprint Retrospective** — Sesión de reflexión post-sprint para identificar qué funcionó bien, qué se podía mejorar y acciones concretas para el siguiente sprint. Generó mejoras iterativas en el proceso de desarrollo'),
  -- Sprint Process EN
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'sprint_process'),
   (SELECT id FROM language WHERE code = 'en'), 'Sprint Ceremonies',
   E'Each sprint followed a structured ceremony cycle ensuring transparency, inspection, and adaptation:\n\n• **Sprint Planning** — Planning session at the beginning of each sprint where user stories were selected from the MoSCoW-prioritized backlog, estimated with story points, and decomposed into assignable technical tasks\n• **Daily Stand-up** — 15-minute daily synchronization meeting where each team member shared progress, impediments, and plan for the day. Maintained sprint status visibility and enabled early blocker detection\n• **Sprint Review** — Functional increment demonstration at the end of each sprint, showcasing completed features (music player, playlist management, authentication, etc.) and gathering feedback\n• **Sprint Retrospective** — Post-sprint reflection session to identify what went well, what could be improved, and concrete actions for the next sprint. Generated iterative improvements in the development process'),

  -- MoSCoW ES
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'moscow'),
   (SELECT id FROM language WHERE code = 'es'), 'Priorización MoSCoW',
   E'El backlog del producto se gestionó utilizando el método de priorización MoSCoW para clasificar todas las historias de usuario y funcionalidades:\n\n• **Must Have** — Funcionalidades críticas sin las cuales la plataforma no funcionaría: reproductor de música global, autenticación con Supabase, API REST de canciones, gestión básica de playlists\n• **Should Have** — Funcionalidades importantes que agregan valor significativo: búsqueda por género/artista/álbum, tematización dinámica Material Design, extracción de metadatos de Spotify/YouTube\n• **Could Have** — Mejoras deseables si el tiempo lo permitía: internacionalización (i18n), extracción de color dominante de portadas, documentación con Compodoc\n• **Won''t Have (this time)** — Funcionalidades pospuestas para futuras iteraciones: sistema de recomendaciones, modo offline, integración con redes sociales\n\nEsta clasificación garantizó que cada sprint entregara valor incremental enfocándose primero en lo esencial.'),
  -- MoSCoW EN
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'moscow'),
   (SELECT id FROM language WHERE code = 'en'), 'MoSCoW Prioritization',
   E'The product backlog was managed using the MoSCoW prioritization method to classify all user stories and features:\n\n• **Must Have** — Critical features without which the platform would not function: global music player, Supabase authentication, songs REST API, basic playlist management\n• **Should Have** — Important features adding significant value: search by genre/artist/album, dynamic Material Design theming, Spotify/YouTube metadata extraction\n• **Could Have** — Desirable improvements if time permitted: internationalization (i18n), dominant color extraction from covers, Compodoc documentation\n• **Won''t Have (this time)** — Features deferred for future iterations: recommendation system, offline mode, social media integration\n\nThis classification ensured each sprint delivered incremental value by focusing on essentials first.'),

  -- Kanban ES
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'kanban'),
   (SELECT id FROM language WHERE code = 'es'), 'Tablero Kanban',
   E'Se implementó un tablero Kanban completo como herramienta visual para gestionar el flujo de trabajo durante cada sprint. El tablero contenía las siguientes columnas:\n\n• **Backlog** — Historias de usuario pendientes priorizadas con MoSCoW\n• **To Do** — Tareas seleccionadas para el sprint actual\n• **In Progress** — Trabajo activo con límite WIP (Work In Progress) para evitar sobrecarga\n• **Code Review** — Tareas completadas en espera de revisión de código por pares\n• **Testing** — Funcionalidades en fase de verificación con tests unitarios y de integración\n• **Done** — Tareas completadas que cumplen con la Definition of Done\n\nEl tablero proporcionaba visibilidad instantánea del estado del sprint, facilitaba la identificación de cuellos de botella en el flujo, y servía como base para las Daily Stand-ups y Sprint Reviews.'),
  -- Kanban EN
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'kanban'),
   (SELECT id FROM language WHERE code = 'en'), 'Kanban Board',
   E'A complete Kanban board was implemented as a visual tool to manage workflow during each sprint. The board contained the following columns:\n\n• **Backlog** — Pending user stories prioritized with MoSCoW\n• **To Do** — Tasks selected for the current sprint\n• **In Progress** — Active work with WIP (Work In Progress) limits to prevent overload\n• **Code Review** — Completed tasks awaiting peer code review\n• **Testing** — Features in verification phase with unit and integration tests\n• **Done** — Completed tasks meeting the Definition of Done\n\nThe board provided instant visibility into sprint status, facilitated bottleneck identification in the workflow, and served as the basis for Daily Stand-ups and Sprint Reviews.'),

  -- Burndown ES
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'burndown'),
   (SELECT id FROM language WHERE code = 'es'), 'Burn Down Charts',
   E'Se generaron Burn Down Charts al final de cada sprint para visualizar el progreso del equipo y medir la velocidad de entrega:\n\n• El eje X representaba los días del sprint y el eje Y los puntos de historia restantes\n• La línea ideal mostraba la velocidad esperada (consumo lineal de puntos) versus la línea real de progreso del equipo\n• Los charts permitían detectar desviaciones tempranamente: si la línea real estaba por encima de la ideal, el sprint tenía riesgo de no completarse\n• Se usaban como insumo en las Sprint Retrospectives para analizar patrones de velocidad y ajustar la capacidad de planificación en sprints futuros\n\nEsta métrica fue clave para mejorar la predictibilidad del equipo sprint a sprint y calibrar las estimaciones de puntos de historia con datos históricos reales.'),
  -- Burndown EN
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'burndown'),
   (SELECT id FROM language WHERE code = 'en'), 'Burn Down Charts',
   E'Burn Down Charts were generated at the end of each sprint to visualize team progress and measure delivery velocity:\n\n• The X-axis represented sprint days and the Y-axis remaining story points\n• The ideal line showed expected velocity (linear point consumption) versus the team''s actual progress line\n• Charts enabled early deviation detection: if the actual line was above the ideal, the sprint was at risk of not completing\n• They were used as input in Sprint Retrospectives to analyze velocity patterns and adjust planning capacity for future sprints\n\nThis metric was key to improving team predictability sprint over sprint and calibrating story point estimates with real historical data.'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'challenges'),
   (SELECT id FROM language WHERE code = 'es'), 'Desafíos y Aprendizajes',
   E'Mantener consistencia arquitectónica entre dos ecosistemas radicalmente diferentes (Python y TypeScript) requirió definir contratos claros entre capas que fueran agnósticos al lenguaje.\n\nLa gestión de submódulos Git presentó desafíos en la sincronización de versiones y la orquestación de CI/CD, resueltos con workflows de GitHub Actions configurados por codebase.\n\nLograr 474+ tests unitarios en el backend exigió diseñar mocks robustos con AsyncMock para operaciones asíncronas y aislar completamente cada capa para tests independientes.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music') AND cs.section_key = 'challenges'),
   (SELECT id FROM language WHERE code = 'en'), 'Challenges & Learnings',
   E'Maintaining architectural consistency across two radically different ecosystems (Python and TypeScript) required defining clear layer contracts that were language-agnostic.\n\nGit submodule management presented challenges in version synchronization and CI/CD orchestration, solved with GitHub Actions workflows configured per codebase.\n\nAchieving 474+ unit tests on the backend demanded designing robust mocks with AsyncMock for async operations and fully isolating each layer for independent testing.')
ON CONFLICT (content_section_id, language_id) DO NOTHING;

-- ============================================================
-- BACKEND: streamflow-music-backend
-- ============================================================
INSERT INTO content_section (entity_type, entity_id, section_key, icon, position, is_archived, is_pinned)
VALUES
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music-backend'), 'overview',      'info',               1, false, true),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music-backend'), 'architecture',  'account_tree',       2, false, true),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music-backend'), 'features',      'featured_play_list', 3, false, false),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music-backend'), 'testing',       'bug_report',         4, false, false),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music-backend'), 'api',           'api',                5, false, false)
ON CONFLICT DO NOTHING;

INSERT INTO content_section_translation (content_section_id, language_id, title, body)
VALUES
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-backend') AND cs.section_key = 'overview'),
   (SELECT id FROM language WHERE code = 'es'), 'Descripción General',
   E'API RESTful construida con Django y Django REST Framework que sirve como núcleo de la plataforma StreamFlow Music. Gestiona todo el ciclo de vida del contenido musical: procesamiento e ingesta de tracks desde fuentes externas (Spotify/YouTube), extracción automática de metadatos de artistas, álbumes y géneros, y almacenamiento normalizado en PostgreSQL.\n\nImplementa un diseño modular de servicios con SongDatabaseService para persistencia de canciones, MediaProcessor para transformación de datos multimedia, y MusicDataConverter para normalización de formatos entre fuentes externas y el modelo de dominio interno.\n\nEl sistema soporta gestión de perfiles de usuario con carga de imágenes a Supabase Storage, operaciones CRUD completas de playlists, y autenticación integrada con Supabase Auth.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-backend') AND cs.section_key = 'overview'),
   (SELECT id FROM language WHERE code = 'en'), 'Overview',
   E'RESTful API built with Django and Django REST Framework that serves as the core of the StreamFlow Music platform. It manages the entire music content lifecycle: track processing and ingestion from external sources (Spotify/YouTube), automatic extraction of artist, album, and genre metadata, and normalized storage in PostgreSQL.\n\nIt implements a modular service design with SongDatabaseService for song persistence, MediaProcessor for multimedia data transformation, and MusicDataConverter for format normalization between external sources and the internal domain model.\n\nThe system supports user profile management with image uploads to Supabase Storage, full playlist CRUD operations, and integrated Supabase Auth authentication.'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-backend') AND cs.section_key = 'architecture'),
   (SELECT id FROM language WHERE code = 'es'), 'Arquitectura',
   E'Arquitectura Limpia estricta aplicada en todas las apps Django con cuatro capas bien definidas:\n\n• **Dominio:** Entidades puras como SongEntity e ISongRepository que encapsulan reglas de negocio sin dependencias externas\n• **Casos de uso:** Orquestadores como SaveTrackAsSongUseCase, GetUserProfileUseCase y UploadProfilePicture que coordinan la lógica de aplicación\n• **Infraestructura:** Modelos ORM de Django, implementaciones concretas de repositorios y mappers entre capas\n• **API:** ViewSets, DTOs serializables con DRF y documentación automática con drf-spectacular\n\nLos settings están modularizados en archivos independientes: base, database, auth, REST framework y Supabase, permitiendo configuración granular por entorno.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-backend') AND cs.section_key = 'architecture'),
   (SELECT id FROM language WHERE code = 'en'), 'Architecture',
   E'Strict Clean Architecture applied across all Django apps with four well-defined layers:\n\n• **Domain:** Pure entities like SongEntity and ISongRepository that encapsulate business rules without external dependencies\n• **Use Cases:** Orchestrators like SaveTrackAsSongUseCase, GetUserProfileUseCase, and UploadProfilePicture that coordinate application logic\n• **Infrastructure:** Django ORM models, concrete repository implementations, and inter-layer mappers\n• **API:** ViewSets, DRF-serializable DTOs, and automatic documentation with drf-spectacular\n\nSettings are modularized into independent files: base, database, auth, REST framework, and Supabase, enabling granular per-environment configuration.'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-backend') AND cs.section_key = 'features'),
   (SELECT id FROM language WHERE code = 'es'), 'Funcionalidades',
   E'• Procesamiento y guardado de tracks musicales desde fuentes Spotify y YouTube con normalización automática de metadatos\n• Extracción inteligente de artistas, álbumes y géneros con deduplicación y relaciones many-to-many\n• Gestión de perfiles de usuario con carga de imágenes a Supabase Storage y validación de formatos\n• Operaciones CRUD completas de playlists con ordenamiento personalizable y paginación\n• Autenticación integrada con Supabase Auth mediante middleware personalizado\n• FilteredViewSetMixin y CRUDViewSetMixin reutilizables que reducen boilerplate en endpoints\n• Documentación de esquemas API generada automáticamente con drf-spectacular\n• Endpoints paginados mediante decorador @paginated_list_endpoint para respuestas consistentes'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-backend') AND cs.section_key = 'features'),
   (SELECT id FROM language WHERE code = 'en'), 'Features',
   E'• Music track processing and saving from Spotify and YouTube sources with automatic metadata normalization\n• Smart extraction of artists, albums, and genres with deduplication and many-to-many relationships\n• User profile management with image uploads to Supabase Storage and format validation\n• Full playlist CRUD operations with customizable sorting and pagination\n• Integrated Supabase Auth authentication via custom middleware\n• Reusable FilteredViewSetMixin and CRUDViewSetMixin that reduce endpoint boilerplate\n• Auto-generated API schema documentation with drf-spectacular\n• Paginated endpoints via @paginated_list_endpoint decorator for consistent responses'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-backend') AND cs.section_key = 'testing'),
   (SELECT id FROM language WHERE code = 'es'), 'Testing',
   E'Más de 474 tests unitarios con cero fallos ejecutados con pytest. La suite de tests cubre exhaustivamente cada capa de la arquitectura:\n\n• **Tests de dominio:** Validación de entidades (SongEntity, ArtistEntity) y reglas de negocio\n• **Tests de casos de uso:** Verificación de flujos completos con mocks de repositorios usando AsyncMock\n• **Tests de DTOs:** TestSongCreateDTO y TestSongMapper validan transformaciones y restricciones de datos\n• **Tests de API:** Endpoints probados con TestClient asegurando respuestas HTTP correctas\n\nIncluye pytest-asyncio para operaciones asíncronas, reportes de cobertura en formato XML integrados con SonarCloud, y un Quality Gate que garantiza umbrales mínimos de cobertura.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-backend') AND cs.section_key = 'testing'),
   (SELECT id FROM language WHERE code = 'en'), 'Testing',
   E'474+ unit tests with zero failures executed with pytest. The test suite exhaustively covers each architecture layer:\n\n• **Domain tests:** Entity validation (SongEntity, ArtistEntity) and business rules\n• **Use case tests:** Full flow verification with repository mocks using AsyncMock\n• **DTO tests:** TestSongCreateDTO and TestSongMapper validate data transformations and constraints\n• **API tests:** Endpoints tested with TestClient ensuring correct HTTP responses\n\nIncludes pytest-asyncio for async operations, XML coverage reports integrated with SonarCloud, and a Quality Gate that enforces minimum coverage thresholds.'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-backend') AND cs.section_key = 'api'),
   (SELECT id FROM language WHERE code = 'es'), 'Diseño de API',
   E'Endpoints RESTful organizados por dominio: canciones, artistas, álbumes, géneros, playlists y perfiles de usuario. Cada recurso utiliza ViewSets (GenreViewSet, UserProfileViewSet) que heredan de los mixins personalizados del proyecto.\n\nToda la API está documentada con decoradores @extend_schema_view de drf-spectacular, generando documentación OpenAPI interactiva accesible desde el navegador.\n\nLos DTOs definen contratos claros de request/response con validación automática mediante serializers. Todas las respuestas de listas usan el decorador @paginated_list_endpoint para formato consistente con metadatos de paginación.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-backend') AND cs.section_key = 'api'),
   (SELECT id FROM language WHERE code = 'en'), 'API Design',
   E'RESTful endpoints organized by domain: songs, artists, albums, genres, playlists, and user profiles. Each resource uses ViewSets (GenreViewSet, UserProfileViewSet) inheriting from the project''s custom mixins.\n\nThe entire API is documented with drf-spectacular @extend_schema_view decorators, generating interactive OpenAPI documentation accessible from the browser.\n\nDTOs define clear request/response contracts with automatic serializer validation. All list responses use the @paginated_list_endpoint decorator for consistent formatting with pagination metadata.')
ON CONFLICT (content_section_id, language_id) DO NOTHING;

-- ============================================================
-- FRONTEND: streamflow-music-frontend
-- ============================================================
INSERT INTO content_section (entity_type, entity_id, section_key, icon, position, is_archived, is_pinned)
VALUES
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music-frontend'), 'overview',      'info',               1, false, true),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music-frontend'), 'architecture',  'account_tree',       2, false, true),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music-frontend'), 'features',      'featured_play_list', 3, false, false),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music-frontend'), 'ui_ux',         'palette',            4, false, false),
  ('project', (SELECT id FROM project WHERE code = 'streamflow-music-frontend'), 'i18n',          'translate',          5, false, false)
ON CONFLICT DO NOTHING;

INSERT INTO content_section_translation (content_section_id, language_id, title, body)
VALUES
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-frontend') AND cs.section_key = 'overview'),
   (SELECT id FROM language WHERE code = 'es'), 'Descripción General',
   E'SPA moderna construida con Angular 19+ y Server-Side Rendering que ofrece una experiencia de usuario fluida para explorar y reproducir música.\n\nEl reproductor de música global permite escuchar contenido mientras se navega por cualquier sección de la aplicación, con controles persistentes de play/pause, siguiente/anterior y barra de progreso.\n\nLa aplicación implementa tematización dinámica con Material Design que permite cambiar entre paletas de colores en tiempo real, autenticación completa con flujos de login/registro vía Supabase, y gestión de playlists con extracción automática de color dominante de las portadas de álbumes.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-frontend') AND cs.section_key = 'overview'),
   (SELECT id FROM language WHERE code = 'en'), 'Overview',
   E'Modern SPA built with Angular 19+ and Server-Side Rendering that offers a smooth user experience for exploring and playing music.\n\nThe global music player allows listening to content while navigating any section of the application, with persistent play/pause, next/previous, and progress bar controls.\n\nThe application implements dynamic Material Design theming that allows switching between color palettes in real time, full authentication with login/register flows via Supabase, and playlist management with automatic dominant color extraction from album covers.'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-frontend') AND cs.section_key = 'architecture'),
   (SELECT id FROM language WHERE code = 'es'), 'Arquitectura',
   E'Diseño dirigido por dominio con separación limpia entre capas:\n\n• **Casos de uso:** AuthSessionUseCase y ChangeLanguageUseCase encapsulan la lógica de aplicación\n• **Repositorios:** Interfaces abstractas como ILanguageRepository con tokens de inyección (LANGUAGE_REPOSITORY_TOKEN) permiten intercambiar implementaciones\n• **Implementaciones:** LanguageRepository maneja persistencia en localStorage con detección automática del idioma del navegador\n• **Servicios de presentación:** LanguageService, GlobalPlayerStateService y MaterialThemeService exponen signals reactivos para vinculación directa con la UI\n\nTodos los componentes son standalone con ChangeDetectionStrategy.OnPush para rendimiento óptimo.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-frontend') AND cs.section_key = 'architecture'),
   (SELECT id FROM language WHERE code = 'en'), 'Architecture',
   E'Domain-driven design with clean layer separation:\n\n• **Use cases:** AuthSessionUseCase and ChangeLanguageUseCase encapsulate application logic\n• **Repositories:** Abstract interfaces like ILanguageRepository with injection tokens (LANGUAGE_REPOSITORY_TOKEN) allow implementation swapping\n• **Implementations:** LanguageRepository handles localStorage persistence with automatic browser language detection\n• **Presentation services:** LanguageService, GlobalPlayerStateService, and MaterialThemeService expose reactive signals for direct UI binding\n\nAll components are standalone with ChangeDetectionStrategy.OnPush for optimal performance.'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-frontend') AND cs.section_key = 'features'),
   (SELECT id FROM language WHERE code = 'es'), 'Funcionalidades',
   E'• Reproductor de música global persistente con GlobalPlayerStateService que mantiene el estado de reproducción entre navegaciones\n• Tematización dinámica Material Design con MaterialThemeService y ThemeDirective que aplican paletas de colores en tiempo real\n• Autenticación completa con flujos de login, registro y recuperación de contraseña vía Supabase\n• Gestión de playlists con extracción automática del color dominante de las portadas\n• Biblioteca musical con tablas ordenables (MusicsTable) y soporte de reproducción inline (MusicsTablePlay)\n• Exploración y búsqueda de contenido con filtros por género, artista y álbum\n• Interceptores HTTP (AuthTokenInterceptor) que inyectan automáticamente tokens de autenticación\n• Documentación técnica generada con Compodoc accesible como sitio web'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-frontend') AND cs.section_key = 'features'),
   (SELECT id FROM language WHERE code = 'en'), 'Features',
   E'• Persistent global music player with GlobalPlayerStateService that maintains playback state across navigations\n• Dynamic Material Design theming with MaterialThemeService and ThemeDirective applying color palettes in real time\n• Full authentication with login, register, and password recovery flows via Supabase\n• Playlist management with automatic dominant color extraction from cover art\n• Music library with sortable tables (MusicsTable) and inline playback support (MusicsTablePlay)\n• Content exploration and search with genre, artist, and album filters\n• HTTP interceptors (AuthTokenInterceptor) that automatically inject authentication tokens\n• Technical documentation generated with Compodoc accessible as a website'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-frontend') AND cs.section_key = 'ui_ux'),
   (SELECT id FROM language WHERE code = 'es'), 'UI/UX',
   E'Sistema de estilos SCSS con variables y módulos (@use, @forward) que permiten composición de estilos sin duplicación. El cambio dinámico de temas se implementa mediante MaterialThemeService que actualiza los tokens de Material Design en tiempo de ejecución.\n\nLos layouts son completamente responsivos con breakpoints adaptados a móvil, tablet y desktop. Las directivas personalizadas como ThemeDirective aplican estilos reactivos basados en el tema seleccionado.\n\nLa integración de MatIcon en tablas musicales proporciona iconografía consistente, y cada componente mantiene estilos encapsulados que evitan colisiones globales.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-frontend') AND cs.section_key = 'ui_ux'),
   (SELECT id FROM language WHERE code = 'en'), 'UI/UX',
   E'SCSS styling system with variables and modules (@use, @forward) enabling style composition without duplication. Dynamic theme switching is implemented via MaterialThemeService that updates Material Design tokens at runtime.\n\nLayouts are fully responsive with breakpoints adapted for mobile, tablet, and desktop. Custom directives like ThemeDirective apply reactive styles based on the selected theme.\n\nMatIcon integration in music tables provides consistent iconography, and each component maintains encapsulated styles that prevent global collisions.'),

  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-frontend') AND cs.section_key = 'i18n'),
   (SELECT id FROM language WHERE code = 'es'), 'Internacionalización',
   E'Soporte completo de internacionalización con ngx-translate para inglés y español. El LanguageRepository detecta automáticamente el idioma del navegador del usuario en la primera visita y persiste la preferencia en localStorage para visitas posteriores.\n\nLanguageService expone signals reactivos que propagan cambios de idioma instantáneamente a toda la UI sin necesidad de recarga. El código es consciente de la plataforma con verificaciones typeof window para garantizar compatibilidad con SSR.'),
  ((SELECT cs.id FROM content_section cs WHERE cs.entity_type = 'project' AND cs.entity_id = (SELECT id FROM project WHERE code = 'streamflow-music-frontend') AND cs.section_key = 'i18n'),
   (SELECT id FROM language WHERE code = 'en'), 'Internationalization',
   E'Full internationalization support with ngx-translate for English and Spanish. LanguageRepository automatically detects the user''s browser language on first visit and persists the preference in localStorage for subsequent visits.\n\nLanguageService exposes reactive signals that propagate language changes instantly across the entire UI without requiring a reload. The code is platform-aware with typeof window checks to ensure SSR compatibility.')
ON CONFLICT (content_section_id, language_id) DO NOTHING;

COMMIT;
