-- =============================================
-- ANALYTICS TABLES
-- =============================================

-- =========================
-- Tabla: visitor_session
-- =========================
CREATE TABLE visitor_session (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  visitor_hash TEXT NOT NULL,
  started_at TIMESTAMPTZ DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ DEFAULT NOW(),
  total_page_views INT DEFAULT 1,
  referrer_source TEXT,
  is_potential_recruiter BOOLEAN DEFAULT FALSE,
  user_agent TEXT,
  device_type TEXT CHECK (device_type IN ('desktop', 'mobile', 'tablet', 'unknown')),
  browser TEXT,
  os TEXT,
  country TEXT,
  city TEXT,
  organization TEXT,
  browser_language TEXT
);

-- =========================
-- Tabla: page_view
-- =========================
CREATE TABLE page_view (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID REFERENCES visitor_session(id) ON DELETE CASCADE,
  page_path TEXT NOT NULL,
  page_title TEXT,
  referrer TEXT,
  duration_seconds INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- Tabla: cv_download
-- =========================

CREATE TABLE cv_download (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID REFERENCES visitor_session(id) ON DELETE CASCADE,
  document_id INT,
  file_name TEXT,
  language TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- Indexes for analytics queries
-- =========================
CREATE INDEX idx_page_view_session ON page_view(session_id);
CREATE INDEX idx_page_view_created_at ON page_view(created_at);
CREATE INDEX idx_page_view_page_path ON page_view(page_path);
CREATE INDEX idx_visitor_session_started_at ON visitor_session(started_at);
CREATE INDEX idx_visitor_session_visitor_hash ON visitor_session(visitor_hash);
CREATE INDEX idx_visitor_session_recruiter ON visitor_session(is_potential_recruiter) WHERE is_potential_recruiter = TRUE;
CREATE INDEX idx_visitor_session_browser_language ON visitor_session(browser_language);

-- =========================
-- Tabla: cv_download
-- =========================
CREATE TABLE cv_download (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID REFERENCES visitor_session(id) ON DELETE CASCADE,
  document_id INT,
  file_name TEXT,
  language TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_cv_download_session ON cv_download(session_id);
CREATE INDEX idx_cv_download_created_at ON cv_download(created_at);

CREATE INDEX IF NOT EXISTS idx_cv_download_session ON cv_download(session_id);
CREATE INDEX IF NOT EXISTS idx_cv_download_created_at ON cv_download(created_at);
