-- =============================================
-- TRANSLATION TABLES
-- =============================================

-- =========================
-- profile_translation
-- =========================
CREATE TABLE profile_translation (
  id SERIAL PRIMARY KEY,
  profile_id UUID REFERENCES profile(id) ON DELETE CASCADE,
  language_id INT NOT NULL REFERENCES language(id),
  about TEXT NOT NULL,
  headline TEXT,

  UNIQUE(profile_id, language_id)
);

-- =========================
-- skill_category_translation
-- =========================
CREATE TABLE skill_category_translation (
  id SERIAL PRIMARY KEY,
  skill_category_id INT REFERENCES skill_category(id) ON DELETE CASCADE,
  language_id INT NOT NULL REFERENCES language(id),
  name TEXT NOT NULL,
  approach TEXT,

  UNIQUE(skill_category_id, language_id)
);

-- =========================
-- skill_translation
-- =========================
CREATE TABLE skill_translation (
  id SERIAL PRIMARY KEY,
  skill_id INT REFERENCES skill(id) ON DELETE CASCADE,
  language_id INT NOT NULL REFERENCES language(id),
  name TEXT NOT NULL,
  description TEXT,

  UNIQUE(skill_id, language_id)
);

-- =========================
-- competitions_translation
-- =========================
CREATE TABLE competitions_translation (
  id SERIAL PRIMARY KEY,
  competitions_id INT REFERENCES competitions(id) ON DELETE CASCADE,
  language_id INT NOT NULL REFERENCES language(id),
  name TEXT NOT NULL,
  description TEXT,
  result TEXT,

  UNIQUE(competitions_id, language_id)
);

-- =========================
-- experience_translation
-- =========================
CREATE TABLE experience_translation (
  id SERIAL PRIMARY KEY,
  experience_id INT REFERENCES experience(id) ON DELETE CASCADE,
  language_id INT NOT NULL REFERENCES language(id),
  role TEXT NOT NULL,
  description TEXT,

  UNIQUE(experience_id, language_id)
);

-- =========================
-- education_translation
  -- =========================
  CREATE TABLE education_translation (
    id SERIAL PRIMARY KEY,
    education_id INT REFERENCES education(id) ON DELETE CASCADE,
    language_id INT NOT NULL REFERENCES language(id),
    degree TEXT NOT NULL,
    field_of_study TEXT,
    description TEXT,

    UNIQUE(education_id, language_id)
  );

-- =========================
-- event_translation
-- =========================
CREATE TABLE event_translation (
  id SERIAL PRIMARY KEY,
  event_id INT REFERENCES event(id) ON DELETE CASCADE,
  language_id INT NOT NULL REFERENCES language(id),
  name TEXT NOT NULL,
  description TEXT,

  UNIQUE(event_id, language_id)
);

-- =========================
-- project_translation
-- =========================
CREATE TABLE project_translation (
  id SERIAL PRIMARY KEY,
  project_id INT REFERENCES project(id) ON DELETE CASCADE,
  language_id INT NOT NULL REFERENCES language(id),
  title TEXT NOT NULL,
  description TEXT,

  UNIQUE(project_id, language_id)
);

-- =========================
-- skill_usages_translation
-- =========================
CREATE TABLE skill_usages_translation (
  id SERIAL PRIMARY KEY,
  skill_usages_id INT REFERENCES skill_usages(id) ON DELETE CASCADE,
  language_id INT NOT NULL REFERENCES language(id),
  notes TEXT,

  UNIQUE(skill_usages_id, language_id)
);

-- =========================
-- content_section_translation
-- =========================
CREATE TABLE content_section_translation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_section_id BIGINT NOT NULL REFERENCES content_section(id) ON DELETE CASCADE,
  language_id BIGINT NOT NULL REFERENCES language(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  UNIQUE (content_section_id, language_id)
);


--- =========================
-- document_translation
-- =========================
CREATE TABLE document_translation (
  id SERIAL PRIMARY KEY,
  document_id INT NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  language_id INT NOT NULL REFERENCES language(id),
  label TEXT,
  description TEXT,

  UNIQUE(document_id, language_id)
);

