-- =============================================================================
-- Content Sections: flexible content blocks for any entity
-- (project, experience, competition, event, education)
-- =============================================================================



-- Translations for sections (multilingual support)
CREATE TABLE IF NOT EXISTS content_section_translation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_section_id BIGINT NOT NULL REFERENCES content_section(id) ON DELETE CASCADE,
  language_id BIGINT NOT NULL REFERENCES language(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  UNIQUE (content_section_id, language_id)
);

