-- =============================================================================
-- Content Sections: flexible content blocks for any entity
-- (project, experience, competition, event, education)
-- =============================================================================

-- Main sections table
CREATE TABLE IF NOT EXISTS content_section (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('project', 'experience', 'competition', 'event', 'education')),
  entity_id BIGINT NOT NULL,
  section_key TEXT NOT NULL DEFAULT 'custom',
  icon TEXT,
  position INT NOT NULL DEFAULT 0,
  is_archived BOOLEAN NOT NULL DEFAULT FALSE,
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Translations for sections (multilingual support)
CREATE TABLE IF NOT EXISTS content_section_translation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_section_id BIGINT NOT NULL REFERENCES content_section(id) ON DELETE CASCADE,
  language_id BIGINT NOT NULL REFERENCES language(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  UNIQUE (content_section_id, language_id)
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_content_section_entity
  ON content_section (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_content_section_translation_section
  ON content_section_translation (content_section_id);
