-- Add browser_language to visitor_session
ALTER TABLE visitor_session
  ADD COLUMN IF NOT EXISTS browser_language TEXT;

CREATE INDEX IF NOT EXISTS idx_visitor_session_browser_language
  ON visitor_session(browser_language);

-- Table: cv_download - tracks each CV download event
CREATE TABLE IF NOT EXISTS cv_download (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID REFERENCES visitor_session(id) ON DELETE CASCADE,
  document_id INT,
  file_name TEXT,
  language TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cv_download_session ON cv_download(session_id);
CREATE INDEX IF NOT EXISTS idx_cv_download_created_at ON cv_download(created_at);
